#!/bin/sh

# Redirect output to stderr.
exec 1>&2

error=0
tmp=$(mktemp)
git diff --cached --name-only --diff-filter=AMR | rg '\.(c|h)$' > "$tmp"

while IFS= read -r file; do
  git show ":${file}" | clang-format --assume-filename="${file}" -Werror --dry-run
  if [ $? -ne 0 ]; then
    error=1
  fi
done < "$tmp"
rm "$tmp"

if [ $error -ne 0 ]; then
  exit 1
fi
