#!/bin/sh

# Redirect output to stderr.
exec 1>&2

error=0
for file in $(git diff --cached --name-only --diff-filter=AMR|rg '\.(c|h)$'); do
  git show ":$file" | clang-format --assume-filename="$file" -Werror --dry-run
  if [ $? -ne 0 ]; then
    error=1
  fi
done

if [ $error -ne 0 ]; then
  exit 1
fi
