#!/bin/sh -e
STORAGE_HOT=/tmp/vms
HOSTNAME=${0##*/}
DISK=$STORAGE_HOT/$HOSTNAME.qcow2
CPU=8
MEMORY=8G

KERNEL=$HOSTNAME-bzImage
CMDLINE='root=/dev/vda1 mitigations=off noapic notsc tsc=unstable'

# -nographic \
# -serial mon:stdio \
exec qemu-system-x86_64 \
  -nodefaults \
  -daemonize \
  -display gtk,gl=on \
  -device virtio-vga-gl,xres=1920,yres=1080 \
  -enable-kvm \
  -machine type=q35,accel=kvm \
  -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0 \
  -cpu host \
  -smp $CPU \
  -m $MEMORY \
  -drive aio=io_uring,file=$DISK,if=virtio \
  -nic user,model=virtio-net-pci \
  -audiodev pipewire,id=snd0 \
  -device ac97,audiodev=snd0 \
  -device usb-ehci -device usb-tablet \
  -name "$HOSTNAME" \
  -kernel "$KERNEL" -append "$CMDLINE" \
  "$@" 
