### COMMON
save-position-on-quit
no-border
msg-module
msg-color
term-osd-bar

### VIDEO
profile=gpu-hq
#hwdec=auto-copy
#target-prim=auto
#target-trc=auto
#interpolation
#video-sync=display-resample
#framedrop=vo
#deband
#deband-grain=80
#dither-depth=8
#scaler-resizes-only
#sigmoid-upscaling
#scale=spline36
#scale-antiring=1.0
#cscale=ewa_lanczossoft
#cscale-antiring=1.0
#dscale=mitchell
#dscale-antiring=1.0
#tscale=mitchell
#tscale-antiring=1.0

### YOUTUBE-DL
ytdl-format='bestvideo[height<=?1080]+bestaudio/best'

### SUBTITLE
sub-auto=fuzzy                  # external subs don't have to match the file name exactly to autoload
sub-file-paths-append=ass       # search for external subs in these relative subdirectories
sub-file-paths-append=srt
sub-file-paths-append=sub
sub-file-paths-append=subs
sub-file-paths-append=subtitles

### LANGUAGE
slang=en,eng
alang=en,eng
ytdl-raw-options=all-subs=,write-sub=,write-auto-sub=

### Profiles
[web]
keep-open
loop-playlist

[music]
shuffle
loop-playlist
