#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='detroit_become_human.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$SAVE_PATH" ]; then
  echo could not find Detroit: Become Human save file
  exit 1
fi

tar xf "$SAVE_PATH" -C "$WINEHOME"

echo "Detroit: Become Human save file loaded from \"$SAVE_PATH\""
