#!/bin/sh
set -o errexit

. ./wine_config.sh

title='Super Mario 3D World'
BACKUP_DIR="$HOME/.local/state/gaming"
BACKUP_FILE='0005000010145d00-sm3dw.tar.zst'
BACKUP_PATH="$BACKUP_DIR/$BACKUP_FILE"

tar xf "$BACKUP_PATH" -C "$WINEHOME" 
echo "$title restored from \"$BACKUP_PATH\""
