#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='overcooked_all_you_can_eat.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$SAVE_PATH" ]; then
  echo could not find Overcooked All You Can Eat save file
  exit 1
fi

tar xf "$SAVE_PATH" -C "$WINEHOME"

echo "Overcooked All You Can Eat save file loaded from \"$SAVE_PATH\""
