#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='cult-of-the-lamb.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$SAVE_PATH" ]; then
  echo 'could not find Cult of the Lamb save file'
  exit 1
fi

tar xf "$SAVE_PATH" -C "$WINEHOME"

echo "Cult of the Lamb save file loaded from \"$SAVE_PATH\""
