#!/bin/sh
set -o errexit

. ./wine_config.sh

title='Elden Ring'
BACKUP_FILE='eldenring.tar.zst'
BACKUP_DIR="$HOME/.local/state/gaming"
BACKUP_PATH="$BACKUP_DIR/$BACKUP_FILE"

if [ ! -e "$BACKUP_PATH" ]; then
  echo "could not find $title save file"
  exit 1
fi

tar xf "$BACKUP_PATH" -C "$WINEHOME"

echo "$title save file loaded from \"$SAVE_PATH\""
