#!/bin/sh
set -o errexit

. ./wine_config.sh

title='No Rest for the Wicked'
BACKUP_FILE='NoRestForTheWicked.tar.zst'

BACKUP_DIR="$HOME/.local/state/gaming"
BACKUP_PATH="$BACKUP_DIR/$BACKUP_FILE"

tar xf "$BACKUP_PATH" -C "$WINEHOME" 
echo "$title restored from \"$BACKUP_PATH\""
