#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='ShipOfFools.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"
APPNAME='Ship of Fools'

if [ ! -e "$SAVE_PATH" ]; then
  echo could not find $APPNAME save file
  exit 1
fi

tar xf "$SAVE_PATH" -C "$WINEHOME"

echo "$APPNAME save file loaded from \"$SAVE_PATH\""
