#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='ghostoftsushima.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$SAVE_PATH" ]; then
  echo "could not find Ghost of Tsushima DIRECTOR'S CUT save file"
  exit 1
fi

tar xf "$SAVE_PATH" -C "$WINEHOME"

echo "Ghost of Tsushima DIRECTOR'S CUT save file loaded from \"$SAVE_PATH\""
