#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='cyberpunk2077.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$SAVE_PATH" ]; then
  echo could not find Cyberpunk 2077 save file
  exit 1
fi

tar xf "$SAVE_PATH" -C "$WINEHOME"

echo "Cyberpunk 2077 save file loaded from \"$SAVE_PATH\""
