#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='sekiro.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$SAVE_PATH" ]; then
  echo 'could not find Sekiro™: Shadows Die Twice save file'
  exit 1
fi

tar xf "$SAVE_PATH" -C "$WINEHOME"

echo "Sekiro™: Shadows Die Twice save file loaded from \"$SAVE_PATH\""
