#!/bin/sh
set -o errexit

. ./wine_config.sh

title='Red Dead Redemption 2'
SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='rdr2.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$SAVE_PATH" ]; then
  echo "could not find $title save file"
  exit 1
fi

tar xf "$SAVE_PATH" -C "$WINEHOME"

echo "$title save file loaded from \"$SAVE_PATH\""
