#!/bin/sh
set -o errexit

. ./wine_config.sh

title='FUMES'
BACKUP_DIR="$HOME/.local/state/gaming"
BACKUP_FILE='fumes.tar.zst'
BACKUP_PATH="$BACKUP_DIR/$BACKUP_FILE"

tar xf "$BACKUP_PATH" -C "$WINEHOME" 
echo "$title restored from \"$BACKUP_PATH\""
