#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='death_squared.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/AppData/LocalLow/SMG Studio/Death Squared" ]; then
  echo Death Squared save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" 'AppData/LocalLow/SMG Studio/Death Squared/' | zstd -19 > "$SAVE_PATH"

echo "Death Squared saves backed into \"$SAVE_PATH\""
