#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='hades.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/Documents/Saved Games/Hades" ]; then
  echo Hades save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" 'Documents/Saved Games/Hades' | zstd -19 > "$SAVE_PATH"

echo "Hades saves backed into \"$SAVE_PATH\""
