#!/bin/sh
set -o errexit

. ./wine_config.sh

title='Mewgenics'
BACKUP_FILE='mewgenics.tar.zst'
SAVE_DIR='AppData/Roaming/Glaiel Games/Mewgenics'

if [ ! -e "$WINEHOME/$SAVE_DIR" ]; then
  echo "$title save file not found"
  exit 1
fi

BACKUP_DIR="$HOME/.local/state/gaming"
BACKUP_PATH="$BACKUP_DIR/$BACKUP_FILE"

mkdir -p "$BACKUP_DIR"

tmpfile=$(mktemp)
tar cf - -C "$WINEHOME" \
  "$SAVE_DIR"           \
  --exclude logs/       \
  --exclude backups/    \
  | zstd --ultra -22 --long > "$tmpfile"
cp "$tmpfile" "$BACKUP_PATH"
rm "$tmpfile"

echo "$title saves backed into \"$BACKUP_PATH\""
