#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='tlou-ii.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/Documents/The Last of Us Part II" ]; then
  echo The Last of Us Part II save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME"                               \
  --exclude *.log                                     \
  --exclude reports/*                                 \
  --exclude attachments/*                             \
  --exclude backup/                                   \
  --exclude *-backup                                  \
  'Documents/The Last of Us Part II'                  \
  'AppData/Roaming/Naughty Dog/The Last of Us Part II'  \
  'AppData/Roaming/Goldberg SteamEmu Saves/settings/user_steam_id.txt' | zstd -19 > "$SAVE_PATH"

echo "The Last of Us Part II saves backed to \"$SAVE_PATH\""
