#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='robocopy.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"


if [ ! -e "$WINEHOME/AppData/Local/RoboCop/Saved" ]; then
  echo Robocop Rouge City save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" 'AppData/Local/RoboCop/Saved' | zstd -19 > "$SAVE_PATH"

echo "Robocop Rouge City saves backed into \"$SAVE_PATH\""
