#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='hollow_knight.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/AppData/LocalLow/Team Cherry/Hollow Knight" ]; then
  echo Hollow Knight save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" 'AppData/LocalLow/Team Cherry/Hollow Knight' | zstd -19 > "$SAVE_PATH"

echo "Hollow Knight saves backed into \"$SAVE_PATH\""
