#!/bin/sh
set -o errexit

. ./wine_config.sh

title='Ratchet Clank: Rift Apart'
SAVE_DIR='Documents/Ratchet & Clank - Rift Apart'
CONFIG_DIR='AppData/Roaming/Insomniac Games/Ratchet & Clank - Rift Apart/'
BACKUP_FILE='riftapart.tar.zst'

BACKUP_DIR="$HOME/.local/state/gaming"
BACKUP_PATH="$BACKUP_DIR/$BACKUP_FILE"

if [ ! -e "$WINEHOME/$SAVE_DIR" ]; then
  echo "$title save file not found"
  exit 1
fi
mkdir -p "$BACKUP_DIR"
tar cf - -C "$WINEHOME"  \
  --exclude Screenshots/ \
  --exclude *.backup*    \
  "$SAVE_DIR"            \
  "$CONFIG_DIR"          \
  | zstd --ultra -22 > "$BACKUP_PATH"

echo "$title saves backed into \"$BACKUP_PATH\""
