#!/bin/sh
set -o errexit

. ./wine_config.sh

title='Remnant 2'
SAVE_DIR='Saved Games/Remnant2'
CONFIG_DIR='AppData/Local/Remnant2'
BACKUP_FILE='remnant2.tar.zst'

BACKUP_DIR="$HOME/.local/state/gaming"
BACKUP_PATH="$BACKUP_DIR/$BACKUP_FILE"

if [ ! -e "$WINEHOME/$SAVE_DIR" ]; then
  echo "$title save file not found"
  exit 1
fi
mkdir -p "$BACKUP_DIR"
tar cf - -C "$WINEHOME"        \
  --exclude CrashReportClient/ \
  --exclude *.bak*             \
  "$SAVE_DIR"                  \
  "$CONFIG_DIR"                \
  | zstd --ultra -22 > "$BACKUP_PATH"

echo "$title saves backed into \"$BACKUP_PATH\""
