#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='bg3.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"
title="Baldur's Gate 3"

if [ ! -e "$WINEHOME/AppData/Local/Larian Studios/Baldur's Gate 3/" ]; then
  echo "$title save file not found"
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" "AppData/Local/Larian Studios/Baldur's Gate 3/" | zstd -19 > "$SAVE_PATH"

echo "$title saves backed into \"$SAVE_PATH\""
