#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='hellblade.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/AppData/Local/HellbladeGame" ]; then
  echo "Hellblade: Senua's Sacrifice save file not found"
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" 'AppData/Local/HellbladeGame' | zstd -19 > "$SAVE_PATH"

echo "Hellblade: Senua's Sacrifice saves backed into \"$SAVE_PATH\""
