#!/bin/sh
set -o errexit

. ./wine_config.sh

title='The Last of Us Part I'
SAVE_DIR='Saved Games/The Last of Us Part I'
BACKUP_FILE='tlou.tar.zst'

BACKUP_DIR="$HOME/.local/state/gaming"
BACKUP_PATH="$BACKUP_DIR/$BACKUP_FILE"

if [ ! -e "$WINEHOME/$SAVE_DIR" ]; then
  echo "$title save file not found"
  exit 1
fi
mkdir -p "$BACKUP_DIR"
tar cf - -C "$WINEHOME"   \
  --exclude log.txt       \
  --exclude user-data.txt \
  "$SAVE_DIR"             \
  | zstd --ultra -22 > "$BACKUP_PATH"

echo "$title saves backed into \"$BACKUP_PATH\""
