#!/bin/sh
set -o errexit

. ./wine_config.sh

title='The Last of Us Part II'
SAVE_DIR='Documents/The Last of Us Part II'
CONFIG_DIR='AppData/Roaming/Naughty Dog/The Last of Us Part II'
BACKUP_FILE='tlou-ii.tar.zst'

BACKUP_DIR="$HOME/.local/state/gaming"
BACKUP_PATH="$BACKUP_DIR/$BACKUP_FILE"

if [ ! -e "$WINEHOME/$SAVE_DIR" ]; then
  echo "$title save file not found"
  exit 1
fi
mkdir -p "$BACKUP_DIR"
tar cf - -C "$WINEHOME"  \
  --exclude *.log        \
  --exclude *.mdmp       \
  --exclude *-backup     \
  --exclude reports/     \
  --exclude attachments/ \
  --exclude Screenshots/ \
  --exclude backup/      \
  "$SAVE_DIR"            \
  "$CONFIG_DIR"          \
  | zstd --ultra -22 > "$BACKUP_PATH"

echo "$title saves backed into \"$BACKUP_PATH\""
