#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='awayout.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/Documents/My Games/A Way Out/" ]; then
  echo A Way Out save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" 'Documents/My Games/A Way Out/' | zstd -19 > "$SAVE_PATH"

echo "A Way Out saves backed into \"$SAVE_PATH\""
