#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='gta5.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/AppData/Roaming/Goldberg SocialClub Emu Saves/GTA V" ]; then
  echo Grand Theft Auto V save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" 'AppData/Roaming/Goldberg SocialClub Emu Saves/GTA V' 'Documents/Rockstar Games/GTA V/settings.xml' | zstd -19 > "$SAVE_PATH"

echo "Grand Theft Auto V saves backed into \"$SAVE_PATH\""
