#!/bin/sh
set -o errexit

. ./wine_config.sh

title='Red Dead Redemption 2'
SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='rdr2.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/AppData/Roaming/.1911/Red Dead Redemption 2/" ]; then
  echo "$title save file not found"
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" 'AppData/Roaming/.1911/Red Dead Redemption 2/' 'Documents/Rockstar Games/Red Dead Redemption 2/Settings/system.xml' | zstd -19 > "$SAVE_PATH"

echo "$title saves backed into \"$SAVE_PATH\""
