#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='hades_ii.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/Saved Games/Hades II" ]; then
  echo Hades II save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" --exclude *.log 'Saved Games/Hades II' | zstd -19 > "$SAVE_PATH"

echo "Hades II saves backed into \"$SAVE_PATH\""
