#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='RainWorld.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/AppData/LocalLow/Videocult/Rain World" ]; then
  echo Rain World save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" 'AppData/LocalLow/Videocult/Rain World' | zstd -19 > "$SAVE_PATH"

echo "Rain World saves backed into \"$SAVE_PATH\""
