#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='ghostoftsushima.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/Documents/Ghost of Tsushima DIRECTOR'S CUT/" ]; then
  echo "Ghost of Tsushima DIRECTOR'S CUT save file not found"
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" "Documents/Ghost of Tsushima DIRECTOR'S CUT/" | zstd -19 > "$SAVE_PATH"

echo "Ghost of Tsushima DIRECTOR'S CUT saves backed into \"$SAVE_PATH\""
