#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='sekiro.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/AppData/Roaming/Sekiro" ]; then
  echo 'Sekiro™: Shadows Die Twice save file not found'
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" 'AppData/Roaming/Sekiro' | zstd -19 > "$SAVE_PATH"

echo "Sekiro™: Shadows Die Twice saves backed into \"$SAVE_PATH\""
