#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='eurotrucksimulator2.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/Documents/Euro Truck Simulator 2/profiles" ]; then
  echo Euro Truck Simulator 2 save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME"                         \
  --exclude profile.bak.sii                     \
  --exclude academy_book_states.bak             \
  --exclude autosave_*/                         \
  --exclude profile.bak.sii                     \
  'Documents/Euro Truck Simulator 2/profiles'   \
  'Documents/Euro Truck Simulator 2/config.cfg' \
  | zstd -19 > "$SAVE_PATH"

echo "Euro Truck Simulator 2 saves backed into \"$SAVE_PATH\""
