#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='braid.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/AppData/Roaming/Braid, Anniversary Edition/" ]; then
  echo Braid, Anniversary Edition save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" 'AppData/Roaming/Braid, Anniversary Edition/' | zstd -19 > "$SAVE_PATH"

echo "Braid, Anniversary Edition saves backed into \"$SAVE_PATH\""
