#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='remnant2.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"


if [ ! -e "$WINEHOME/Saved Games/Remnant2" ]; then
  echo Remnant 2 save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" --exclude CrashReportClient.ini 'Saved Games/Remnant2' 'AppData/Local/Remnant2' 'AppData/Roaming/Goldberg SteamEmu Saves/settings/user_steam_id.txt' | zstd -19 > "$SAVE_PATH"

echo "Remnant 2 saves backed into \"$SAVE_PATH\""
