#!/bin/sh
set -o errexit

. ./wine_config.sh

title="Cemu"

SAVE_DIR='AppData/Roaming/Cemu'
if [ ! -e "$WINEHOME/$SAVE_DIR" ]; then
  echo "$title save file not found"
  exit 1
fi

BACKUP_DIR="$HOME/.local/state/gaming"
BACKUP_FILE='cemu.tar.zst'
BACKUP_PATH="$BACKUP_DIR/$BACKUP_FILE"

mkdir -p "$BACKUP_DIR"

TMPFILE=$(mktemp)
tar cf - -C "$WINEHOME"               \
  "$SAVE_DIR/controllerProfiles/"     \
  "$SAVE_DIR/graphicPacks/"           \
  "$SAVE_DIR/shaderCache/"            \
  "$SAVE_DIR/mlc01/usr/save/system/"  \
  "$SAVE_DIR/settings.xml"            \
  "$SAVE_DIR/title_list_cache.xml"    \
  | zstd -3 > "$TMPFILE"
cp "$TMPFILE" "$BACKUP_PATH"
rm "$TMPFILE"

echo "$title saves backed into \"$BACKUP_PATH\""
