#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='doometernal.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/AppData/Roaming/Goldberg SteamEmu Saves/782330" ]; then
  echo DOOM Eternal save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" 'AppData/Roaming/Goldberg SteamEmu Saves/782330' 'Saved Games/id Software/DOOMEternal' | zstd -19 > "$SAVE_PATH"

echo "DOOM Eternal saves backed into \"$SAVE_PATH\""
