#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='overcooked_all_you_can_eat.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/AppData/LocalLow/Team17/Overcooked All You Can Eat/" ]; then
  echo Overcooked All You Can Eat save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" 'AppData/LocalLow/Team17/Overcooked All You Can Eat/' | zstd -19 > "$SAVE_PATH"

echo "Overcooked All You Can Eat saves backed to \"$SAVE_PATH\""
