#!/bin/sh
set -o errexit

. ./wine_config.sh

title='Sackboy - A Big Adventure'

SAVE_DIR='Saved Games/Sackboy'
CONFIG_DIR='AppData/Local/GingerBread/Saved/Config/WindowsNoEditor'
if [ ! -e "$WINEHOME/$SAVE_DIR" ]; then
  echo "$title save file not found"
  exit 1
fi

BACKUP_DIR="$HOME/.local/state/gaming"
BACKUP_FILE='sackboy.tar.zst'
BACKUP_PATH="$BACKUP_DIR/$BACKUP_FILE"

mkdir -p "$BACKUP_DIR"

tmpfile=$(mktemp)
tar cf - -C "$WINEHOME" \
  "$SAVE_DIR"           \
  "$CONFIG_DIR"         \
  | zstd --ultra -22 --long > "$tmpfile"
cp "$tmpfile" "$BACKUP_PATH"
rm "$tmpfile"

echo "$title saves backed into \"$BACKUP_PATH\""
