#!/bin/sh
set -o errexit

. ./wine_config.sh

title='Super Mario 3D World'

MLC_DIR='AppData/Roaming/Cemu/mlc01'
PersistentIdHead=80000001
if [ -f "$WINEHOME/$MLC_DIR/usr/save/system/act/persisid.dat" ]; then
  grep -oE 'PersistentIdHead=[0-9]{8}' "$WINEHOME/$MLC_DIR/usr/save/system/act/persisid.dat" | while IFS='=' read key value; do
    PersistentIdHead="$value"
  done
fi
SAVE_DIR="$MLC_DIR/usr/save/00050000/10145d00/user/$userid"
if [ ! -e "$WINEHOME/$SAVE_DIR" ]; then
  echo "$title save file not found"
  exit 1
fi

BACKUP_DIR="$HOME/.local/state/gaming"
BACKUP_FILE='0005000010145d00-sm3dw.tar.zst'
BACKUP_PATH="$BACKUP_DIR/$BACKUP_FILE"

mkdir -p "$BACKUP_DIR"

tar cf - -C "$WINEHOME" "$SAVE_DIR" | zstd --ultra -22 --long > "$BACKUP_PATH"

echo "$title saves backed into \"$BACKUP_PATH\""
