#!/bin/sh
set -o errexit

. ./wine_config.sh

title='Detroit: Become Human'
SAVE_DIR='Saved Games/Quantic Dream/Detroit Become Human'
BACKUP_FILE='detroit_become_human.tar.zst'

BACKUP_DIR="$HOME/.local/state/gaming"
BACKUP_PATH="$BACKUP_DIR/$BACKUP_FILE"

if [ ! -e "$WINEHOME/$SAVE_DIR" ]; then
  echo "$title save file not found"
  exit 1
fi

mkdir -p "$BACKUP_DIR"
tar cf - -C "$WINEHOME" \
  "$SAVE_DIR"           \
  | zstd --ultra -22 > "$BACKUP_PATH"

echo "$title saves backed into \"$BACKUP_PATH\""
