#!/bin/sh
set -o errexit

. ./wine_config.sh

title='REANIMAL'
BACKUP_FILE='reanimal.tar.zst'
SAVE_DIR='AppData/Roaming/Goldberg SteamEmu Saves/2129530'
CONFIG_DIR='AppData/Local/Everholm/Saved/Config/Windows'

if [ ! -e "$WINEHOME/$SAVE_DIR" ]; then
  echo "$title save file not found"
  exit 1
fi

BACKUP_DIR="$HOME/.local/state/gaming"
BACKUP_PATH="$BACKUP_DIR/$BACKUP_FILE"

mkdir -p "$BACKUP_DIR"

tmpfile=$(mktemp)
tar cf - -C "$WINEHOME"        \
  --exclude Logs/              \
  --exclude Crashes/           \
  --exclude CrashReportClient/ \
  "$SAVE_DIR"                  \
  "$CONFIG_DIR"                \
  | zstd --ultra -22 --long > "$tmpfile"
cp "$tmpfile" "$BACKUP_PATH"
rm "$tmpfile"

echo "$title saves backed into \"$BACKUP_PATH\""
