#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='ittakestwo.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/AppData/Local/ItTakesTwo" ]; then
  echo It Takes Two save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" 'AppData/Local/ItTakesTwo/' | zstd -19 > "$SAVE_PATH"

echo "It Takes Two saves backed into \"$SAVE_PATH\""
