#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='SplitFiction.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"

if [ ! -e "$WINEHOME/AppData/Local/SplitFiction" ]; then
  echo Split Fiction save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" 'AppData/Local/SplitFiction' | zstd -19 > "$SAVE_PATH"

echo "Split Fiction saves backed into \"$SAVE_PATH\""
