#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='eldenring.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"


if [ ! -e "$WINEHOME/AppData/Roaming/EldenRing" ]; then
  echo Elden Ring save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" 'AppData/Roaming/EldenRing' 'AppData/Roaming/Goldberg SteamEmu Saves/settings/user_steam_id.txt' | zstd -19 > "$SAVE_PATH"

echo "Elden Ring saves backed into \"$SAVE_PATH\""
