#!/bin/sh
set -o errexit

. ./wine_config.sh

SAVE_DIR="$HOME/.local/state/gaming"
SAVE_FILE='ShipOfFools.tar.zst'
SAVE_PATH="$SAVE_DIR/$SAVE_FILE"
APPNAME='Ship of Fools'
TARGET='AppData/LocalLow/Fika Productions/ShipOfFools/'

if [ ! -e "$WINEHOME/$TARGET" ]; then
  echo $APPNAME save file not found
  exit 1
fi

mkdir -p "$SAVE_DIR"

tar cf - -C "$WINEHOME" "$TARGET" | zstd -19 > "$SAVE_PATH"

echo "$APPNAME saves backed into \"$SAVE_PATH\""
